name: Secrets example
on: push
jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: Test
        run: |
          if [ "$HERO" == "BALAYYA" ]
          then
            echo "Got secret"
          fi
          if [ "$HEROINE" == "SRUTHI" ]
          then
            echo "Got secret something else"
          fi
        env: 
          HERO_SECURE: ${{ secrets.JAI_BALAYYA }}
          HEROINE_SECURE: ${{ secrets.JAI_JAI_SRUTHI }}
